Funcionarios-Web/WebSite.Funcionarios/Models/BuscaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebSite.Funcionarios.Models
{
    public class BuscaViewModel
    {
        public string Nome { get; set; }
        public int DepartamentoId { get; set; }
        public string Status { get; set; }

    }
}

Funcionarios-Web/WebSite.Funcionarios/Models/DepartamentoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebSite.Funcionarios.Models
{
    public class DepartamentoViewModel
    {
        public int DepartamentoId { get; set; }
        public string Descricao { get; set; }
    }
}

Funcionarios-Web/WebSite.Funcionarios/Models/ErrorViewModel.cs
using System;

namespace WebSite.Funcionarios.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Funcionarios-Web/WebSite.Funcionarios/Models/FuncaoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebSite.Funcionarios.Models
{
    public class FuncaoViewModel
    {
        public int FuncaoId { get; set; }
        public string Descricao { get; set; }
    }
}

Funcionarios-Web/WebSite.Funcionarios/Models/FuncionarioViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebSite.Funcionarios.Models
{
    public class FuncionarioViewModel
    {
        [RegularExpression("^[0-9]*$", ErrorMessage = "Só é permitido números!")]
        [Required(ErrorMessage = "O campo CPF é inválido")]
        public string Cpf { get; set; }

        [RegularExpression("^[a-zA-Z\u00C0-\u00FF ]*$", ErrorMessage ="Só é permitido letras!")]
        [Required(ErrorMessage = "O campo Nome é inválido")]
        public string Nome { get; set; }
        
        [Required(ErrorMessage = "O campo Idade é obrigatório")]
        public int Idade { get; set; }

        [Required(ErrorMessage = "O campo Status é obrigatório")]
        public string Status { get; set; }

        [Required(ErrorMessage = "O campo Departamento é obrigatório")]
        public int DepartamentoId { get; set; }


        [Required(ErrorMessage = "O campo Função é obrigatório")]
        public int FuncaoId { get; set; }

        [Required(ErrorMessage = "O campo Dependentes é obrigatório")]
        public int Dependentes { get; set; }
        public double Salario { get; set; }
    }
}

Funcionarios-Web/WebSite.Funcionarios/Controllers/FuncionarioController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebSite.Funcionarios.Models;
using WebSiteFuncionarios.Data.Context;

namespace WebSite.Funcionarios.Controllers
{
    public class FuncionarioController : Controller
    {
        private readonly ILogger<FuncionarioController> _logger;

        private readonly Connections.ConsultasEntity _consultas;

        public FuncionarioController(ILogger<FuncionarioController> logger, FuncionarioContext dbContext)
        {
            _consultas = new Connections.ConsultasEntity(dbContext);
            _logger = logger;
        }
        public IActionResult Index()
        {

            ViewData["Funcoes"] = _consultas.SelectFuncoes();

            ViewData["Departamentos"] = _consultas.SelectDepartamentos();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Cadastrar(FuncionarioViewModel model)
        {
            try
            {
                _consultas.InsertFuncionario(model);
            }
            catch(Exception ex)
            {
                TempData["Error"] = $"Ocorreu um erro: {ex.Message}";

                ViewData["Funcoes"] = _consultas.SelectFuncoes();

                ViewData["Departamentos"] = _consultas.SelectDepartamentos();

                return View("Index");
            }

            TempData["Success"] = "Funcionário cadastrado com Sucesso";

            return RedirectToAction("Index");
        }
    }
}

Funcionarios-Web/WebSite.Funcionarios/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebSite.Funcionarios.Models;
using WebSiteFuncionarios.Data.Context;
using WebSiteFuncionarios.Data.Entities;

namespace WebSite.Funcionarios.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            
            return View();
        }

        
    }
}

Funcionarios-Web/WebSite.Funcionarios/Controllers/ListarFuncionarioController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebSite.Funcionarios.Models;
using WebSiteFuncionarios.Data.Context;

namespace WebSite.Funcionarios.Controllers
{
    public class ListarFuncionarioController : Controller
    {
        private readonly ILogger<ListarFuncionarioController> _logger;

        private readonly Connections.ConsultasEntity _consultas;

        public ListarFuncionarioController(ILogger<ListarFuncionarioController> logger, FuncionarioContext dbContext)
        {
            _consultas = new Connections.ConsultasEntity(dbContext);
            _logger = logger;
        }
        public IActionResult Index()
        {

            ViewData["Departamentos"] = _consultas.SelectDepartamentos();

            return View();
        }

        [HttpPost]
        public ActionResult Buscar(BuscaViewModel model)
        {

            var registros = _consultas.SelectFuncionarios(model);

            if (model.Status != "Desligado" && String.IsNullOrEmpty(model.Status))
            {
                ViewData["Registros"] = registros.FindAll(f => f.Status != "Desligado");
            }
            else if(model.Status == "Ativo")
            {
                ViewData["Registros"] = registros.FindAll(f => f.Status == "Ativo");
            }
            else if(model.Status == "Ausente")
            {
                ViewData["Registros"] = registros.FindAll(f => f.Status == "Ausente");
            }
            else
            {
                ViewData["Registros"] = registros.FindAll(f => f.Status == "Desligado");
            }
            

            ViewData["Departamentos"] = _consultas.SelectDepartamentos();

            return View("Index");
        }

        public ActionResult Alterar(string cpf, string nome, int idade, string status,int dependentes, int departamentoId, int funcaoId)
        {
            ViewData["Funcoes"] = _consultas.SelectFuncoes();

            ViewData["Departamentos"] = _consultas.SelectDepartamentos();

            FuncionarioViewModel model = new FuncionarioViewModel
            {
                Cpf = cpf,
                Nome = nome,
                Idade = idade,
                Status = status,
                Dependentes = dependentes,
                DepartamentoId = departamentoId,
                FuncaoId = funcaoId
            };

            return View("Alterar", model);
        }

        public ActionResult AtualizarBanco(FuncionarioViewModel model)
        {

            try
            {
                _consultas.UpdateFuncionario(model);
            }
            catch (Exception ex)
            {
                TempData["Error"] = $"Ocorreu um erro: {ex.Message}";

                return View("Index");
            }

            TempData["Success"] = "Funcionário atualizado com Sucesso";

            return RedirectToAction("Index");

        }

        public ActionResult Excluir(string cpf)
        {

            try
            {
                _consultas.DeletarFuncionario(cpf);
            }
            catch (Exception ex)
            {
                TempData["Error"] = $"Ocorreu um erro: {ex.Message}";

                return View("Index");
            }

            TempData["Success"] = "Funcionário deletado com Sucesso";

            return RedirectToAction("Index");
        }

    }
}

Funcionarios-Web/WebSite.Funcionarios/Views/Funcionario/Index.cshtml
@{
    ViewData["Title"] = "Cadastrar Funcionário";
}

@model WebSite.Funcionarios.Models.FuncionarioViewModel

<div class="container">
    <div class="row">
        <div class="col">
            <p class="h1 text-info">@ViewData["Title"]</p>
        </div>
    </div>
</div>

<div class="container-fluid">



    <div class="col-12">

        @if (TempData["Success"] != null)
        {
            <p class="alert alert-success" id="successMessage">@TempData["Success"]</p>
        }

        @if (TempData["Error"] != null)
        {
            <p class="alert alert-danger" id="successMessage">@TempData["Error"]</p>
        }

        <form method="post" asp-action="Cadastrar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="row">
                <div class="col-sm-6">
                    <label asp-for="Nome" class="form-label">Nome(*):</label>
                    <input asp-for="Nome" type="text" class="form-control" placeholder="Digite o nome...">
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>

            </div>

            <div class="row">
                <div class="col-sm-6">
                    <label asp-for="Cpf" class="form-label">CPF(*):</label>
                    <input asp-for="Cpf" type="text" class="form-control" placeholder="Digite o CPF...">
                    <span asp-validation-for="Cpf" class="text-danger"></span>
                </div>

            </div>

            <div class="row">
                <div class="col-sm-3">
                    <label asp-for="Idade" class="form-label">Idade(*):</label>
                    <input asp-for="Idade" type="number" class="form-control" placeholder="Digite a idade...">
                    <span asp-validation-for="Idade" class="text-danger"></span>
                </div>
                <div class="col-3">
                    <div class="form-group">
                        <label asp-for="Status">Status(*):</label>
                        <select asp-for="Status" class="custom-select" placeholder="Selecione">
                            <option value="">Selecione</option>
                            <option value="Ativo">Ativo</option>
                            <option value="Ausente">Ausente</option>
                            <option value="Desligado">Desligado</option>
                        </select>
                        <span asp-validation-for="Status" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-3">
                    <div class="form-group">
                        <label asp-for="Dependentes">Número de Dependentes(*):</label>
                        <select asp-for="Dependentes" class="custom-select" placeholder="Selecione">
                            <option value="">Selecione</option>
                            <option value="0">0</option>
                            <option value="1">1-2</option>
                            <option value="2">2-3</option>
                            <option value="3">3+</option>
                        </select>
                        <span asp-validation-for="Dependentes" class="text-danger"></span>
                    </div>
                </div>

            </div>

            <div class="row">
                <div class="col-6">
                    <div class="form-group">
                        <label asp-for="DepartamentoId">Departamento(*):</label>
                        <select asp-for="DepartamentoId" class="custom-select" placeholder="Selecione">
                            <option value="">Selecione</option>
                            @if (ViewData["Departamentos"] != null)
                            {
                                foreach (var item in (List<WebSite.Funcionarios.Models.DepartamentoViewModel>)ViewData["Departamentos"])
                                {
                                    <option value="@item.DepartamentoId">@item.Descricao</option>
                                }
                            }
                        </select>
                        <span asp-validation-for="DepartamentoId" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-6">
                    <div class="form-group">
                        <label asp-for="FuncaoId">Função(*):</label>
                        <select asp-for="FuncaoId" class="custom-select" placeholder="Selecione">
                            <option value="">Selecione</option>
                            @if (ViewData["Funcoes"] != null)
                            {
                                foreach (var item in (List<WebSite.Funcionarios.Models.FuncaoViewModel>)ViewData["Funcoes"])
                                {
                                    <option value="@item.FuncaoId">@item.Descricao</option>
                                }
                            }
                        </select>
                        <span asp-validation-for="FuncaoId" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row">

                <div class="col-auto">
                    <button type="submit" class="btn btn-primary mb-3">Cadastrar</button>
                </div>

            </div>

        </form>

    </div>
</div>

Funcionarios-Web/WebSite.Funcionarios/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Funcionarios-Web/WebSite.Funcionarios/Views/ListarFuncionario/Alterar.cshtml
@{
    ViewData["Title"] = "Alterar Funcionário";
}

@model WebSite.Funcionarios.Models.FuncionarioViewModel

<div class="container">
    <div class="row">
        <div class="col">
            <p class="h1 text-info">@ViewData["Title"]</p>
        </div>
    </div>
</div>

<div class="container-fluid">

    <div class="col-12">

        <form method="post" asp-action="AtualizarBanco">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="row">
                <div class="col-sm-6">
                    <label asp-for="Cpf" class="form-label">CPF(*):</label>
                    <input asp-for="Cpf" type="text" class="form-control" placeholder="Digite o CPF..." readonly>
                    <span asp-validation-for="Cpf" class="text-danger"></span>
                </div>

            </div>

            <div class="row">
                <div class="col-sm-6">
                    <label asp-for="Nome" class="form-label">Nome(*):</label>
                    <input asp-for="Nome" type="text" class="form-control" placeholder="Digite o nome...">
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>

            </div>


            <div class="row">
                <div class="col-sm-3">
                    <label asp-for="Idade" class="form-label">Idade(*):</label>
                    <input asp-for="Idade" type="number" class="form-control" placeholder="Digite a idade...">
                    <span asp-validation-for="Idade" class="text-danger"></span>
                </div>

                <div class="col-3">
                    <div class="form-group">
                        <label asp-for="Status">Status(*):</label>
                        <select asp-for="Status" class="custom-select" placeholder="Selecione">
                            <option value="">Selecione</option>
                            <option value="Ativo">Ativo</option>
                            <option value="Ausente">Ausente</option>
                            <option value="Desligado">Desligado</option>
                        </select>
                        <span asp-validation-for="Status" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-3">
                    <div class="form-group">
                        <label asp-for="Dependentes">Número de Dependentes(*):</label>
                        <select asp-for="Dependentes" class="custom-select" placeholder="Selecione">
                            <option value="">Selecione</option>
                            <option value="0">0</option>
                            <option value="1">1-2</option>
                            <option value="2">2-3</option>
                            <option value="3">3+</option>
                        </select>
                        <span asp-validation-for="Dependentes" class="text-danger"></span>
                    </div>
                </div>

            </div>

            <div class="row">
                <div class="col-6">
                    <div class="form-group">
                        <label asp-for="DepartamentoId">Departamento(*):</label>
                        <select asp-for="DepartamentoId" class="custom-select" placeholder="Selecione">
                            <option value="">Selecione</option>
                            @if (ViewData["Departamentos"] != null)
                            {
                                foreach (var item in (List<WebSite.Funcionarios.Models.DepartamentoViewModel>)ViewData["Departamentos"])
                                {
                                    <option value="@item.DepartamentoId">@item.Descricao</option>
                                }
                            }
                        </select>
                        <span asp-validation-for="DepartamentoId" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-6">
                    <div class="form-group">
                        <label asp-for="FuncaoId">Função(*):</label>
                        <select asp-for="FuncaoId" class="custom-select" placeholder="Selecione">
                            <option value="">Selecione</option>
                            @if (ViewData["Funcoes"] != null)
                            {
                                foreach (var item in (List<WebSite.Funcionarios.Models.FuncaoViewModel>)ViewData["Funcoes"])
                                {
                                    <option value="@item.FuncaoId">@item.Descricao</option>
                                }
                            }
                        </select>
                        <span asp-validation-for="FuncaoId" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row">

                <div class="col-auto">
                    <button type="submit" class="btn btn-primary mb-3">Salvar</button>
                </div>

            </div>

        </form>

    </div>
</div>

Funcionarios-Web/WebSite.Funcionarios/Views/ListarFuncionario/Index.cshtml
@{
    ViewData["Title"] = "Listar Funcionários";
}

@section scripts{

    <script>


            $(".excluir").click(function () {

                $("#modalConfirmacao").modal('show');

                var cpf = $(this).attr("data-id");
                var link = "@Url.Action("Excluir")";

                link += `?cpf=${cpf}`;

                $(".confirma").click(function () {
                    location.href = link;
                })

            });

        
    </script>
}

@model WebSite.Funcionarios.Models.BuscaViewModel

<div class="container">
    <div class="row">
        <div class="col">
            <p class="h1 text-info">@ViewData["Title"]</p>
        </div>
    </div>
</div>

<div class="container-fluid">

    <div class="col-12">

        @if (TempData["Success"] != null)
        {
            <p class="alert alert-success" id="successMessage">@TempData["Success"]</p>
        }
        @if (TempData["Error"] != null)
        {
            <p class="alert alert-danger" id="successMessage">@TempData["Error"]</p>
        }
        <div class="row">

            <form method="post" asp-action="Buscar">
                <div class="row">

                    <div class="col-6">
                        <label asp-for="Nome" class="form-label">Nome(*): </label>
                        <input asp-for="Nome" type="text" class="form-control" placeholder="">

                    </div>

                    <div class="col-3">
                        <div class="form-group">
                            <label asp-for="DepartamentoId">Departamento(*):</label>
                            <select asp-for="DepartamentoId" class="custom-select" placeholder="Selecione">
                                <option value="0">Selecione</option>
                                @if (ViewData["Departamentos"] != null)
                                {
                                    foreach (var item in (List<WebSite.Funcionarios.Models.DepartamentoViewModel>)ViewData["Departamentos"])
                                    {
                                        <option value="@item.DepartamentoId">@item.Descricao</option>
                                    }
                                }
                            </select>

                        </div>
                    </div>

                    <div class="col-3">
                        <div class="form-group">
                            <label asp-for="Status">Status(*):</label>
                            <select asp-for="Status" class="custom-select" placeholder="Selecione">
                                <option value="">Selecione</option>
                                <option value="Ativo">Ativo</option>
                                <option value="Ausente">Ausente</option>
                                <option value="Desligado">Desligado</option>
                            </select>

                        </div>
                    </div>

                </div>
                <div class="row">

                    <div class="col-auto">
                        <button type="submit" class="btn btn-primary mb-3">Pesquisar <i class="fa-solid fa-magnifying-glass"></i></button>
                    </div>

                </div>

            </form>

            @if (ViewData["Registros"] != null)
            {
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">CPF</th>
                            <th scope="col">Nome</th>
                            <th scope="col">Status</th>
                            <th scope="col">Salário</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>

                        @foreach (var item in (List<FuncionarioViewModel>)ViewData["Registros"])
                        {
                            if (item.Status == "Ativo")
                            {
                                <tr class="table-success">
                                    <th>@item.Cpf</th>
                                    <td>@item.Nome</td>
                                    <td>@item.Status</td>
                                    <td>@item.Salario</td>
                                    <td>
                                        <a href="@Url.Action("Alterar", new { cpf = item.Cpf, nome = item.Nome, idade = item.Idade,status = item.Status, dependentes = item.Dependentes, departamentoId  = item.DepartamentoId, funcaoId = item.FuncaoId })" class="btn btn-info"><i class="fa-solid fa-pencil"></i></a>
                                        <button data-id="@item.Cpf" class="excluir btn btn-danger"><i class="fa-solid fa-trash-can"></i></button>
                                    </td>
                                </tr>
                            }
                            if (item.Status == "Ausente")
                            {
                                <tr class="table-warning">
                                    <th>@item.Cpf</th>
                                    <td>@item.Nome</td>
                                    <td>@item.Status</td>
                                    <td>@item.Salario</td>
                                    <td>
                                        <a href="@Url.Action("Alterar", new { cpf = item.Cpf, nome = item.Nome, idade = item.Idade,status = item.Status,dependentes = item.Dependentes, departamentoId  = item.DepartamentoId, funcaoId = item.FuncaoId })" class="btn btn-info"><i class="fa-solid fa-pencil"></i></a>
                                        <button data-id="@item.Cpf" class="excluir btn btn-danger"><i class="fa-solid fa-trash-can"></i></button>
                                    </td>
                                </tr>
                            }
                            if (item.Status == "Desligado")
                            {
                                <tr class="table-danger">
                                    <th>@item.Cpf</th>
                                    <td>@item.Nome</td>
                                    <td>@item.Status</td>
                                    <td>@item.Salario</td>
                                    <td>
                                        <a href="@Url.Action("Alterar", new { cpf = item.Cpf, nome = item.Nome, idade = item.Idade,status = item.Status,dependentes = item.Dependentes, departamentoId  = item.DepartamentoId, funcaoId = item.FuncaoId })" class="btn btn-info"><i class="fa-solid fa-pencil"></i></a>
                                        <button data-id="@item.Cpf" class="excluir btn btn-danger"><i class="fa-solid fa-trash-can"></i></button>
                                    </td>
                                </tr>
                            }

                        }


                    </tbody>
                </table>
            }

        </div>

    </div>

</div>


<div class="modal" id="modalConfirmacao" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirmação</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Deseja Excluir o Funcionário?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="confirma btn btn-primary">Sim</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
            </div>
        </div>
    </div>
</div>

Funcionarios-Web/WebSite.Funcionarios/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema de Funcionarios</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sistema de Funcionarios</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Funcionario" asp-action="Index">Cadastrar Funcionário</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ListarFuncionario" asp-action="Index">Listar Funcionários</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebSite.Funcionarios - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/font-awesome/js/fontawesome.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>